[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/traficom/*"
  to = "https://trafi2.stat.fi/PXWeb/api/v1/en/TraFi/TraFi__Kaytettyna_maahantuodut/:splat"
  status = 200
  force = true
